env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - next/core-web-vitals
  - plugin:testing-library/react
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jest/recommended
  - plugin:jest/style

parser: "@typescript-eslint/parser"
parserOptions:
  project: './tsconfig.json'

  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
  - jest

rules:
  indent: 0
  "@typescript-eslint/no-explicit-any": off
  '@typescript-eslint/explicit-module-boundary-types': off
  linebreak-style: 0
  "import/no-extraneous-dependencies": 1
  quotes: 0
  semi: 0
